// Configuración de preguntas del cuestionario OEUK
import { getTranslation } from './i18n/translations'

export const getQuestionSteps = (language = 'en') => {
  const t = (key) => getTranslation(language, key);

  return [
  // SECTION: BACKGROUND INFORMATION
  {
    id: "surname",
    section: t('background'),
    question: t('questions.surname'),
    required: true,
    type: "text",
    field: "surname",
  },
  {
    id: "first_name",
    section: t('background'),
    question: t('questions.first_name'),
    required: true,
    type: "text",
    field: "first_name",
  },
  {
    id: "id_type",
    section: t('background'),
    question: t('questions.id_type'),
    type: "select",
    field: "id_type",
    options: t('options.idTypes'),
  },
  {
    id: "id_number",
    section: t('background'),
    question: t('questions.id_number'),
    type: "text",
    field: "id_number",
  },
  {
    id: "date_of_birth",
    section: t('background'),
    question: t('questions.date_of_birth'),
    type: "date",
    field: "date_of_birth",
  },
  {
    id: "address",
    section: t('background'),
    question: t('questions.address'),
    type: "text",
    field: "address",
  },
  {
    id: "city",
    section: t('background'),
    question: t('questions.city'),
    type: "text",
    field: "city",
  },
  {
    id: "telephone",
    section: t('background'),
    question: t('questions.telephone'),
    type: "number",
    field: "telephone",
  },
  {
    id: "exam_date",
    section: t('background'),
    question: t('questions.exam_date'),
    type: "date",
    field: "exam_date",
  },

  // SECTION: CURRENT JOB DATA
  {
    id: "current_employer",
    section: t('currentJob'),
    question: t('questions.current_employer'),
    type: "text",
    field: "current_employer",
  },
  {
    id: "position_held",
    section: t('currentJob'),
    question: t('questions.position_held'),
    type: "text",
    field: "position_held",
  },
  {
    id: "time_in_office_months",
    section: t('currentJob'),
    question: t('questions.time_in_office_months'),
    type: "number",
    field: "time_in_office_months",
    tooltip: t('tooltips.time_in_office_months'),
  },
  {
    id: "contract_type",
    section: t('currentJob'),
    question: t('questions.contract_type'),
    type: "select",
    field: "contract_type",
    options: t('options.contractTypes'),
  },
  {
    id: "country_work",
    section: t('currentJob'),
    question: t('questions.country_work'),
    type: "text",
    field: "country_work",
  },
  {
    id: "date_of_travel",
    section: t('currentJob'),
    question: t('questions.date_of_travel'),
    type: "date",
    field: "date_of_travel",
  },
  {
    id: "shift_scheme",
    section: t('currentJob'),
    question: t('questions.shift_scheme'),
    type: "select",
    field: "shift_scheme",
    options: t('options.shiftSchemes'),
    tooltip: t('tooltips.shift_scheme'),
  },
  {
    id: "work_involves",
    section: t('currentJob'),
    question: t('questions.work_involves'),
    type: "checkbox-group",
    fields: [
      "work_involves_food",
      "work_involves_cranes",
      "work_involves_ert",
      "work_involves_inu",
    ],
    labels: t('options.workInvolves'),
    tooltip: t('tooltips.work_involves'),
  },

  // SECTION: PREVIOUS CERTIFICATIONS
  {
    id: "recent_oeuk_exam",
    section: t('certifications'),
    question: t('questions.recent_oeuk_exam'),
    type: "yesno",
    field: "has_recent_oeuk_exam",
  },
  {
    id: "recent_oeuk_exam_date",
    section: t('certifications'),
    question: t('questions.recent_oeuk_exam_date'),
    type: "date",
    field: "recent_oeuk_exam_date",
    showIf: (formData) => formData.has_recent_oeuk_exam === "Yes" || formData.has_recent_oeuk_exam === "Sí",
  },
  {
    id: "recent_oeuk_provider",
    section: t('certifications'),
    question: t('questions.recent_oeuk_provider'),
    type: "text",
    field: "recent_oeuk_exam_provider",
    showIf: (formData) => formData.has_recent_oeuk_exam === "Yes" || formData.has_recent_oeuk_exam === "Sí",
  },
  {
    id: "recent_training",
    section: t('certifications'),
    question: t('questions.recent_training'),
    type: "yesno",
    field: "has_recent_training",
  },
  {
    id: "recent_training_date",
    section: t('certifications'),
    question: t('questions.recent_training_date'),
    type: "date",
    field: "recent_training_date",
    showIf: (formData) => formData.has_recent_training === "Yes" || formData.has_recent_training === "Sí",
  },
  {
    id: "recent_training_provider",
    section: t('certifications'),
    question: t('questions.recent_training_provider'),
    type: "text",
    field: "recent_training_provider",
    showIf: (formData) => formData.has_recent_training === "Yes" || formData.has_recent_training === "Sí",
  },
  {
    id: "next_foet",
    section: t('certifications'),
    question: t('questions.next_foet'),
    type: "yesno",
    field: "has_next_foet",
    tooltip: t('tooltips.next_foet'),
  },
  {
    id: "next_foet_date",
    section: t('certifications'),
    question: t('questions.next_foet_date'),
    type: "date",
    field: "next_foet_bosiet_date",
    showIf: (formData) => formData.has_next_foet === "Yes" || formData.has_next_foet === "Sí",
  },

  // SECTION: HEALTH HABITS
  {
    id: "smoking",
    section: t('healthHabits'),
    question: t('questions.smoking'),
    type: "radio",
    field: "smoking_status",
    options: t('options.smokingStatuses'),
  },
  {
    id: "smoking_quantity",
    section: t('healthHabits'),
    question: t('questions.smoking_quantity'),
    type: "number",
    field: "smoking_quantity_day",
    showIf: (formData) => {
      const status = formData.smoking_status;
      return status === "Currently" || status === "Actualmente" ||
             status === "Former smoker" || status === "Ex fumador";
    },
  },
  {
    id: "smoking_years",
    section: t('healthHabits'),
    question: t('questions.smoking_years'),
    type: "number",
    field: "smoking_time_years",
    showIf: (formData) => {
      const status = formData.smoking_status;
      return status === "Currently" || status === "Actualmente" ||
             status === "Former smoker" || status === "Ex fumador";
    },
  },
  {
    id: "alcohol",
    section: t('healthHabits'),
    question: t('questions.alcohol'),
    type: "select",
    field: "alcohol_consumption",
    options: t('options.alcoholLevels'),
  },
  {
    id: "physical_activity",
    section: t('healthHabits'),
    question: t('questions.physical_activity'),
    type: "select",
    field: "physical_activity",
    options: t('options.physicalActivities'),
  },
  {
    id: "physical_frequency",
    section: t('healthHabits'),
    question: t('questions.physical_frequency'),
    type: "select",
    field: "physical_activity_frequency",
    options: t('options.activityFrequencies'),
    showIf: (formData) => {
      const activity = formData.physical_activity;
      return activity && activity !== "None" && activity !== "Ninguna";
    },
  },
  {
    id: "physical_duration",
    section: t('healthHabits'),
    question: t('questions.physical_duration'),
    type: "select",
    field: "physical_activity_duration",
    options: t('options.activityDurations'),
    showIf: (formData) => {
      const activity = formData.physical_activity;
      return activity && activity !== "None" && activity !== "Ninguna";
    },
  },

  // SECTION: OCCUPATIONAL MEDICAL HISTORY
  {
    id: "occupational_diseases",
    section: t('occupationalHistory'),
    question: t('questions.occupational_diseases'),
    type: "textarea",
    field: "occupational_diseases",
    placeholder: t('placeholders.occupational_diseases'),
  },
  {
    id: "workplace_accidents",
    section: t('occupationalHistory'),
    question: t('questions.workplace_accidents'),
    type: "textarea",
    field: "workplace_accidents",
    placeholder: t('placeholders.workplace_accidents'),
  },
  {
    id: "medical_evacuations",
    section: t('occupationalHistory'),
    question: t('questions.medical_evacuations'),
    type: "textarea",
    field: "medical_evacuations",
    placeholder: t('placeholders.medical_evacuations'),
  },
  {
    id: "missed_trips",
    section: t('occupationalHistory'),
    question: t('questions.missed_trips'),
    type: "textarea",
    field: "missed_trips",
    placeholder: t('placeholders.missed_trips'),
    tooltip: t('tooltips.missed_trips'),
  },
  {
    id: "previous_oeuk",
    section: t('occupationalHistory'),
    question: t('questions.previous_oeuk'),
    type: "checkbox-group",
    fields: ["previous_oeuk_deferred", "previous_oeuk_restricted"],
    labels: t('options.previousOeukLabels'),
    tooltip: t('tooltips.previous_oeuk'),
  },

  // SECTION: CURRENT MEDICAL HISTORY
  {
    id: "current_diagnoses",
    section: t('currentMedical'),
    question: t('questions.current_diagnoses'),
    type: "textarea",
    field: "current_diagnoses",
    placeholder: t('placeholders.current_diagnoses'),
  },
  {
    id: "undiagnosed_symptoms",
    section: t('currentMedical'),
    question: t('questions.undiagnosed_symptoms'),
    type: "textarea",
    field: "undiagnosed_symptoms",
    placeholder: t('placeholders.undiagnosed_symptoms'),
  },
  {
    id: "recurring_appointments",
    section: t('currentMedical'),
    question: t('questions.recurring_appointments'),
    type: "textarea",
    field: "recurring_appointments",
  },
  {
    id: "current_medication",
    section: t('currentMedical'),
    question: t('questions.current_medication'),
    type: "textarea",
    field: "current_medication",
    placeholder: t('placeholders.current_medication'),
  },

  // SECTION: MEDICAL HISTORY - Common conditions
  {
    id: "hospital_admissions",
    section: t('medicalHistory'),
    question: t('questions.hospital_admissions'),
    type: "textarea",
    field: "hospital_admissions",
  },
  {
    id: "surgeries",
    section: t('medicalHistory'),
    question: t('questions.surgeries'),
    type: "textarea",
    field: "surgeries",
  },
  {
    id: "chronic_diseases",
    section: t('medicalHistory'),
    question: t('questions.chronic_diseases'),
    type: "textarea",
    field: "chronic_diseases",
  },
  {
    id: "high_blood_pressure",
    section: t('medicalHistory'),
    question: t('questions.high_blood_pressure'),
    type: "yesno",
    field: "high_blood_pressure",
  },
  {
    id: "cardiovascular",
    section: t('medicalHistory'),
    question: t('questions.cardiovascular'),
    type: "yesno",
    field: "cardiovascular_disease",
  },
  {
    id: "neurological",
    section: t('medicalHistory'),
    question: t('questions.neurological'),
    type: "yesno",
    field: "neurological_disease",
  },
  {
    id: "anxiety_depression",
    section: t('medicalHistory'),
    question: t('questions.anxiety_depression'),
    type: "yesno",
    field: "anxiety_depression",
  },
  {
    id: "alcohol_disorder",
    section: t('medicalHistory'),
    question: t('questions.alcohol_disorder'),
    type: "yesno",
    field: "alcohol_use_disorder",
  },
  {
    id: "substance_abuse",
    section: t('medicalHistory'),
    question: t('questions.substance_abuse'),
    type: "yesno",
    field: "substance_abuse",
  },
  {
    id: "asthma",
    section: t('medicalHistory'),
    question: t('questions.asthma'),
    type: "yesno",
    field: "asthma",
  },
  {
    id: "copd",
    section: t('medicalHistory'),
    question: t('questions.copd'),
    type: "yesno",
    field: "copd",
  },
  {
    id: "pneumothorax",
    section: t('medicalHistory'),
    question: t('questions.pneumothorax'),
    type: "yesno",
    field: "pneumothorax",
  },
  {
    id: "diabetes",
    section: t('medicalHistory'),
    question: t('questions.diabetes'),
    type: "yesno",
    field: "diabetes",
  },
  {
    id: "thyroid",
    section: t('medicalHistory'),
    question: t('questions.thyroid'),
    type: "yesno",
    field: "thyroid_disorder",
  },
  {
    id: "addisons",
    section: t('medicalHistory'),
    question: t('questions.addisons'),
    type: "yesno",
    field: "addisons_disease",
  },
  {
    id: "peptic_ulcer",
    section: t('medicalHistory'),
    question: t('questions.peptic_ulcer'),
    type: "yesno",
    field: "peptic_ulcer",
  },
  {
    id: "ibd",
    section: t('medicalHistory'),
    question: t('questions.ibd'),
    type: "yesno",
    field: "inflammatory_bowel_disease",
  },
  {
    id: "pancreatitis",
    section: t('medicalHistory'),
    question: t('questions.pancreatitis'),
    type: "yesno",
    field: "pancreatitis",
  },
  {
    id: "liver",
    section: t('medicalHistory'),
    question: t('questions.liver'),
    type: "yesno",
    field: "liver_disease",
  },
  {
    id: "amputation",
    section: t('medicalHistory'),
    question: t('questions.amputation'),
    type: "yesno",
    field: "limb_amputation",
  },
  {
    id: "arthritis",
    section: t('medicalHistory'),
    question: t('questions.arthritis'),
    type: "yesno",
    field: "arthritis",
  },
  {
    id: "joint_replacement",
    section: t('medicalHistory'),
    question: t('questions.joint_replacement'),
    type: "yesno",
    field: "joint_replacement",
  },
  {
    id: "muscle_pain",
    section: t('medicalHistory'),
    question: t('questions.muscle_pain'),
    type: "yesno",
    field: "muscle_pain",
  },
  {
    id: "back_pain",
    section: t('medicalHistory'),
    question: t('questions.back_pain'),
    type: "yesno",
    field: "back_pain",
  },
  {
    id: "dermatitis",
    section: t('medicalHistory'),
    question: t('questions.dermatitis'),
    type: "yesno",
    field: "dermatitis",
  },
  {
    id: "kidney",
    section: t('medicalHistory'),
    question: t('questions.kidney'),
    type: "yesno",
    field: "kidney_disease",
  },
  {
    id: "blood_disorders",
    section: t('medicalHistory'),
    question: t('questions.blood_disorders'),
    type: "yesno",
    field: "blood_disorders",
  },
  {
    id: "transplantation",
    section: t('medicalHistory'),
    question: t('questions.transplantation'),
    type: "yesno",
    field: "organ_transplantation",
  },
  {
    id: "cancer",
    section: t('medicalHistory'),
    question: t('questions.cancer'),
    type: "yesno",
    field: "cancer",
  },
  {
    id: "infectious",
    section: t('medicalHistory'),
    question: t('questions.infectious'),
    type: "yesno",
    field: "infectious_disease",
  },
  {
    id: "hearing",
    section: t('medicalHistory'),
    question: t('questions.hearing'),
    type: "yesno",
    field: "hearing_loss",
  },
  {
    id: "dizziness",
    section: t('medicalHistory'),
    question: t('questions.dizziness'),
    type: "yesno",
    field: "dizziness_vertigo",
  },
  {
    id: "eardrum",
    section: t('medicalHistory'),
    question: t('questions.eardrum'),
    type: "yesno",
    field: "eardrum_perforation",
  },
  {
    id: "visual",
    section: t('medicalHistory'),
    question: t('questions.visual'),
    type: "yesno",
    field: "visual_impairment",
  },
  {
    id: "dental",
    section: t('medicalHistory'),
    question: t('questions.dental'),
    type: "yesno",
    field: "caries_dental",
  },
  {
    id: "allergic",
    section: t('medicalHistory'),
    question: t('questions.allergic'),
    type: "yesno",
    field: "allergic_disorders",
  },
  {
    id: "immunodeficiency",
    section: t('medicalHistory'),
    question: t('questions.immunodeficiency'),
    type: "yesno",
    field: "immunodeficiency",
  },
  {
    id: "pregnancy",
    section: t('medicalHistory'),
    question: t('questions.pregnancy'),
    type: "yesno",
    field: "current_pregnancy",
  },
  {
    id: "self_disability",
    section: t('medicalHistory'),
    question: t('questions.self_disability'),
    type: "yesno",
    field: "self_perception_disability",
    tooltip: t('tooltips.self_disability'),
  },
  {
    id: "classified_disabled",
    section: t('medicalHistory'),
    question: t('questions.classified_disabled'),
    type: "yesno",
    field: "classified_disabled",
    tooltip: t('tooltips.classified_disabled'),
  },

  // SECTION: PHOTO AND SIGNATURE
  {
    id: "photo",
    section: t('verification'),
    question: t('questions.photo'),
    type: "photo",
    field: "photo_base64",
  },
  {
    id: "signature",
    section: t('verification'),
    question: t('questions.signature'),
    type: "signature",
    field: "signature_base64",
  },
];
};

export const initialFormData = {
  // Background
  surname: "",
  first_name: "",
  id_type: "",
  id_number: "",
  date_of_birth: "",
  address: "",
  city: "",
  telephone: "",
  exam_date: "",
  // Current Job Data
  current_employer: "",
  position_held: "",
  time_in_office_months: "",
  contract_type: "",
  country_work: "",
  date_of_travel: "",
  shift_scheme: "",
  work_involves_food: false,
  work_involves_cranes: false,
  work_involves_ert: false,
  work_involves_inu: false,
  employment_history: "",
  // Previous Certifications
  has_recent_oeuk_exam: "",
  recent_oeuk_exam_date: "",
  recent_oeuk_exam_provider: "",
  has_recent_training: "",
  recent_training_date: "",
  recent_training_provider: "",
  has_next_foet: "",
  next_foet_bosiet_date: "",
  // Health Habits
  smoking_status: "",
  smoking_quantity_day: "",
  smoking_time_years: "",
  alcohol_consumption: "",
  physical_activity: "",
  physical_activity_frequency: "",
  physical_activity_duration: "",
  // Occupational Medical History
  occupational_diseases: "",
  workplace_accidents: "",
  medical_evacuations: "",
  missed_trips: "",
  previous_oeuk_deferred: false,
  previous_oeuk_restricted: false,
  // Current Medical History
  current_diagnoses: "",
  undiagnosed_symptoms: "",
  recurring_appointments: "",
  current_medication: "",
  // Medical History
  hospital_admissions: "",
  surgeries: "",
  chronic_diseases: "",
  high_blood_pressure: "",
  cardiovascular_disease: "",
  neurological_disease: "",
  anxiety_depression: "",
  alcohol_use_disorder: "",
  substance_abuse: "",
  asthma: "",
  copd: "",
  pneumothorax: "",
  diabetes: "",
  thyroid_disorder: "",
  addisons_disease: "",
  peptic_ulcer: "",
  inflammatory_bowel_disease: "",
  pancreatitis: "",
  liver_disease: "",
  limb_amputation: "",
  arthritis: "",
  joint_replacement: "",
  muscle_pain: "",
  back_pain: "",
  dermatitis: "",
  kidney_disease: "",
  blood_disorders: "",
  organ_transplantation: "",
  cancer: "",
  infectious_disease: "",
  hearing_loss: "",
  dizziness_vertigo: "",
  eardrum_perforation: "",
  visual_impairment: "",
  caries_dental: "",
  allergic_disorders: "",
  immunodeficiency: "",
  current_pregnancy: "",
  self_perception_disability: "",
  classified_disabled: "",
  // Photo and Signature
  photo_base64: "",
  signature_base64: "",
};
