// Configuración de preguntas del cuestionario OEUK
export const questionSteps = [
  // SECTION: BACKGROUND INFORMATION
  {
    id: "surname",
    section: "Background",
    question: "Surname",
    required: true,
    type: "text",
    field: "surname",
  },
  {
    id: "first_name",
    section: "Background",
    question: "First name",
    required: true,
    type: "text",
    field: "first_name",
  },
  {
    id: "id_type",
    section: "Background",
    question: "ID Type",
    type: "select",
    field: "id_type",
    options: ["Passport", "National ID", "Driver License", "Other"],
  },
  {
    id: "id_number",
    section: "Background",
    question: "ID Number",
    type: "text",
    field: "id_number",
  },
  {
    id: "date_of_birth",
    section: "Background",
    question: "Date of birth",
    type: "date",
    field: "date_of_birth",
  },
  {
    id: "address",
    section: "Background",
    question: "Address",
    type: "text",
    field: "address",
  },
  {
    id: "city",
    section: "Background",
    question: "City",
    type: "text",
    field: "city",
  },
  {
    id: "telephone",
    section: "Background",
    question: "Telephone",
    type: "number",
    field: "telephone",
  },
  {
    id: "exam_date",
    section: "Background",
    question: "Exam Date",
    type: "date",
    field: "exam_date",
  },

  // SECTION: CURRENT JOB DATA
  {
    id: "current_employer",
    section: "Current Job",
    question: "Current Employer",
    type: "text",
    field: "current_employer",
  },
  {
    id: "position_held",
    section: "Current Job",
    question: "Position held",
    type: "text",
    field: "position_held",
  },
  {
    id: "time_in_office_months",
    section: "Current Job",
    question: "Time in office (months)",
    type: "number",
    field: "time_in_office_months",
  },
  {
    id: "contract_type",
    section: "Current Job",
    question: "Contract type",
    type: "select",
    field: "contract_type",
    options: ["Fixed", "Eventual"],
  },
  {
    id: "country_work",
    section: "Current Job",
    question: "Country where you will work?",
    type: "text",
    field: "country_work",
  },
  {
    id: "date_of_travel",
    section: "Current Job",
    question: "Date of travel?",
    type: "date",
    field: "date_of_travel",
  },
  {
    id: "shift_scheme",
    section: "Current Job",
    question: "Shift Scheme",
    type: "select",
    field: "shift_scheme",
    options: ["2:3", "3:3", "Other"],
  },
  {
    id: "work_involves",
    section: "Current Job",
    question: "The work involves",
    type: "checkbox-group",
    fields: [
      "work_involves_food",
      "work_involves_cranes",
      "work_involves_ert",
      "work_involves_inu",
    ],
    labels: ["Food", "Op. Cranes", "ERT", "INU"],
  },

  // SECTION: PREVIOUS CERTIFICATIONS
  {
    id: "recent_oeuk_exam",
    section: "Certifications",
    question: "Have you had a previous OEUK medical exam?",
    type: "yesno",
    field: "has_recent_oeuk_exam",
  },
  {
    id: "recent_oeuk_exam_date",
    section: "Certifications",
    question: "Date of the most recent OEUK medical exam",
    type: "date",
    field: "recent_oeuk_exam_date",
    showIf: (formData) => formData.has_recent_oeuk_exam === "Yes",
  },
  {
    id: "recent_oeuk_provider",
    section: "Certifications",
    question: "Provider of the most recent OEUK medical exam",
    type: "text",
    field: "recent_oeuk_exam_provider",
    showIf: (formData) => formData.has_recent_oeuk_exam === "Yes",
  },
  {
    id: "recent_training",
    section: "Certifications",
    question: "Have you had a previous training assessment?",
    type: "yesno",
    field: "has_recent_training",
  },
  {
    id: "recent_training_date",
    section: "Certifications",
    question: "Date of the most recent training assessment",
    type: "date",
    field: "recent_training_date",
    showIf: (formData) => formData.has_recent_training === "Yes",
  },
  {
    id: "recent_training_provider",
    section: "Certifications",
    question: "Provider of the most recent training assessment",
    type: "text",
    field: "recent_training_provider",
    showIf: (formData) => formData.has_recent_training === "Yes",
  },
  {
    id: "next_foet",
    section: "Certifications",
    question: "Do you have a scheduled FOET/BOSIET exam?",
    type: "yesno",
    field: "has_next_foet",
  },
  {
    id: "next_foet_date",
    section: "Certifications",
    question: "Date of the next FOET/BOSIET exam",
    type: "date",
    field: "next_foet_bosiet_date",
    showIf: (formData) => formData.has_next_foet === "Yes",
  },

  // SECTION: HEALTH HABITS
  {
    id: "smoking",
    section: "Health Habits",
    question: "Do you currently smoke or vape?",
    type: "radio",
    field: "smoking_status",
    options: ["Currently", "Former smoker", "Never"],
  },
  {
    id: "smoking_quantity",
    section: "Health Habits",
    question: "If you smoke/vape, how many per day?",
    type: "number",
    field: "smoking_quantity_day",
    showIf: (formData) => formData.smoking_status === "Currently" || formData.smoking_status === "Former smoker",
  },
  {
    id: "smoking_years",
    section: "Health Habits",
    question: "How many years have you smoked?",
    type: "number",
    field: "smoking_time_years",
    showIf: (formData) => formData.smoking_status === "Currently" || formData.smoking_status === "Former smoker",
  },
  {
    id: "alcohol",
    section: "Health Habits",
    question: "Alcohol consumption",
    type: "select",
    field: "alcohol_consumption",
    options: ["Never", "Occasionally (1-2 drinks/week)", "Moderate (3-7 drinks/week)", "Heavy (>7 drinks/week)", "Prefer not to say"],
  },
  {
    id: "physical_activity",
    section: "Health Habits",
    question: "Do you engage in leisure-time physical activity?",
    type: "select",
    field: "physical_activity",
    options: ["None", "Walking", "Running", "Gym/Fitness", "Sports (specify)", "Cycling", "Swimming", "Other"],
  },
  {
    id: "physical_frequency",
    section: "Health Habits",
    question: "How many times per week?",
    type: "select",
    field: "physical_activity_frequency",
    options: ["1-2 times", "3-4 times", "5-6 times", "Daily"],
    showIf: (formData) => formData.physical_activity && formData.physical_activity !== "None",
  },
  {
    id: "physical_duration",
    section: "Health Habits",
    question: "Duration per session",
    type: "select",
    field: "physical_activity_duration",
    options: ["Less than 30 min", "30-60 min", "1-2 hours", "More than 2 hours"],
    showIf: (formData) => formData.physical_activity && formData.physical_activity !== "None",
  },

  // SECTION: OCCUPATIONAL MEDICAL HISTORY
  {
    id: "occupational_diseases",
    section: "Occupational History",
    question: "Have you had any occupational diseases?",
    type: "textarea",
    field: "occupational_diseases",
    placeholder: "Please describe if any",
  },
  {
    id: "workplace_accidents",
    section: "Occupational History",
    question: "Have you had any workplace accidents?",
    type: "textarea",
    field: "workplace_accidents",
    placeholder: "Please describe if any",
  },
  {
    id: "medical_evacuations",
    section: "Occupational History",
    question: "Have you had any medical evacuations?",
    type: "textarea",
    field: "medical_evacuations",
    placeholder: "Please describe if any",
  },
  {
    id: "missed_trips",
    section: "Occupational History",
    question: "Have you had any missed trips?",
    type: "textarea",
    field: "missed_trips",
    placeholder: "Please describe if any",
  },
  {
    id: "previous_oeuk",
    section: "Occupational History",
    question: "Previous OEUK exams",
    type: "checkbox-group",
    fields: ["previous_oeuk_deferred", "previous_oeuk_restricted"],
    labels: ["Deferred", "Restricted"],
  },

  // SECTION: CURRENT MEDICAL HISTORY
  {
    id: "current_diagnoses",
    section: "Current Medical",
    question: "Current Medical Diagnoses",
    type: "textarea",
    field: "current_diagnoses",
    placeholder: "List any current medical diagnoses",
  },
  {
    id: "undiagnosed_symptoms",
    section: "Current Medical",
    question: "Undiagnosed symptoms",
    type: "textarea",
    field: "undiagnosed_symptoms",
    placeholder: "Describe any symptoms you are experiencing",
  },
  {
    id: "recurring_appointments",
    section: "Current Medical",
    question: "Actual or planned recurring appointments",
    type: "textarea",
    field: "recurring_appointments",
  },
  {
    id: "current_medication",
    section: "Current Medical",
    question: "Current medication",
    type: "textarea",
    field: "current_medication",
    placeholder: "List all current medications",
  },

  // SECTION: MEDICAL HISTORY - Common conditions
  {
    id: "hospital_admissions",
    section: "Medical History",
    question: "Have you had any hospital admissions?",
    type: "textarea",
    field: "hospital_admissions",
  },
  {
    id: "surgeries",
    section: "Medical History",
    question: "Have you had any surgeries?",
    type: "textarea",
    field: "surgeries",
  },
  {
    id: "chronic_diseases",
    section: "Medical History",
    question: "Do you have any chronic diseases?",
    type: "textarea",
    field: "chronic_diseases",
  },
  {
    id: "high_blood_pressure",
    section: "Medical History",
    question: "High blood pressure?",
    type: "yesno",
    field: "high_blood_pressure",
  },
  {
    id: "cardiovascular",
    section: "Medical History",
    question: "Cardiovascular disease?",
    type: "yesno",
    field: "cardiovascular_disease",
  },
  {
    id: "neurological",
    section: "Medical History",
    question: "Neurological disease?",
    type: "yesno",
    field: "neurological_disease",
  },
  {
    id: "anxiety_depression",
    section: "Medical History",
    question: "Anxiety/depression?",
    type: "yesno",
    field: "anxiety_depression",
  },
  {
    id: "alcohol_disorder",
    section: "Medical History",
    question: "Alcohol use disorder?",
    type: "yesno",
    field: "alcohol_use_disorder",
  },
  {
    id: "substance_abuse",
    section: "Medical History",
    question: "Substance abuse?",
    type: "yesno",
    field: "substance_abuse",
  },
  {
    id: "asthma",
    section: "Medical History",
    question: "Asthma?",
    type: "yesno",
    field: "asthma",
  },
  {
    id: "copd",
    section: "Medical History",
    question: "COPD?",
    type: "yesno",
    field: "copd",
  },
  {
    id: "pneumothorax",
    section: "Medical History",
    question: "Pneumothorax?",
    type: "yesno",
    field: "pneumothorax",
  },
  {
    id: "diabetes",
    section: "Medical History",
    question: "Diabetes?",
    type: "yesno",
    field: "diabetes",
  },
  {
    id: "thyroid",
    section: "Medical History",
    question: "Thyroid disorder?",
    type: "yesno",
    field: "thyroid_disorder",
  },
  {
    id: "addisons",
    section: "Medical History",
    question: "Addison's disease?",
    type: "yesno",
    field: "addisons_disease",
  },
  {
    id: "peptic_ulcer",
    section: "Medical History",
    question: "Peptic ulcer?",
    type: "yesno",
    field: "peptic_ulcer",
  },
  {
    id: "ibd",
    section: "Medical History",
    question: "Inflammatory bowel disease?",
    type: "yesno",
    field: "inflammatory_bowel_disease",
  },
  {
    id: "pancreatitis",
    section: "Medical History",
    question: "Pancreatitis?",
    type: "yesno",
    field: "pancreatitis",
  },
  {
    id: "liver",
    section: "Medical History",
    question: "Liver disease?",
    type: "yesno",
    field: "liver_disease",
  },
  {
    id: "amputation",
    section: "Medical History",
    question: "Limb amputation?",
    type: "yesno",
    field: "limb_amputation",
  },
  {
    id: "arthritis",
    section: "Medical History",
    question: "Arthritis?",
    type: "yesno",
    field: "arthritis",
  },
  {
    id: "joint_replacement",
    section: "Medical History",
    question: "Joint replacement?",
    type: "yesno",
    field: "joint_replacement",
  },
  {
    id: "muscle_pain",
    section: "Medical History",
    question: "Muscle pain, myalgias?",
    type: "yesno",
    field: "muscle_pain",
  },
  {
    id: "back_pain",
    section: "Medical History",
    question: "Back pain, Low back pain?",
    type: "yesno",
    field: "back_pain",
  },
  {
    id: "dermatitis",
    section: "Medical History",
    question: "Dermatitis?",
    type: "yesno",
    field: "dermatitis",
  },
  {
    id: "kidney",
    section: "Medical History",
    question: "Kidney disease, stones?",
    type: "yesno",
    field: "kidney_disease",
  },
  {
    id: "blood_disorders",
    section: "Medical History",
    question: "Blood disorders, anemia?",
    type: "yesno",
    field: "blood_disorders",
  },
  {
    id: "transplantation",
    section: "Medical History",
    question: "Organ transplantation?",
    type: "yesno",
    field: "organ_transplantation",
  },
  {
    id: "cancer",
    section: "Medical History",
    question: "Cancer?",
    type: "yesno",
    field: "cancer",
  },
  {
    id: "infectious",
    section: "Medical History",
    question: "Infectious disease: TB, HIV?",
    type: "yesno",
    field: "infectious_disease",
  },
  {
    id: "hearing",
    section: "Medical History",
    question: "Hearing loss?",
    type: "yesno",
    field: "hearing_loss",
  },
  {
    id: "dizziness",
    section: "Medical History",
    question: "Dizziness/vertigo?",
    type: "yesno",
    field: "dizziness_vertigo",
  },
  {
    id: "eardrum",
    section: "Medical History",
    question: "Perforation of the eardrum?",
    type: "yesno",
    field: "eardrum_perforation",
  },
  {
    id: "visual",
    section: "Medical History",
    question: "Visual impairment?",
    type: "yesno",
    field: "visual_impairment",
  },
  {
    id: "dental",
    section: "Medical History",
    question: "Caries dental?",
    type: "yesno",
    field: "caries_dental",
  },
  {
    id: "allergic",
    section: "Medical History",
    question: "Allergic Disorders?",
    type: "yesno",
    field: "allergic_disorders",
  },
  {
    id: "immunodeficiency",
    section: "Medical History",
    question: "Immunodeficiency?",
    type: "yesno",
    field: "immunodeficiency",
  },
  {
    id: "pregnancy",
    section: "Medical History",
    question: "Current pregnancy?",
    type: "yesno",
    field: "current_pregnancy",
  },
  {
    id: "self_disability",
    section: "Medical History",
    question: "Self-perception of disability?",
    type: "yesno",
    field: "self_perception_disability",
  },
  {
    id: "classified_disabled",
    section: "Medical History",
    question: "Classification as disabled?",
    type: "yesno",
    field: "classified_disabled",
  },
];

export const initialFormData = {
  // Background
  surname: "",
  first_name: "",
  id_type: "",
  id_number: "",
  date_of_birth: "",
  address: "",
  city: "",
  telephone: "",
  exam_date: "",
  // Current Job Data
  current_employer: "",
  position_held: "",
  time_in_office_months: "",
  contract_type: "",
  country_work: "",
  date_of_travel: "",
  shift_scheme: "",
  work_involves_food: false,
  work_involves_cranes: false,
  work_involves_ert: false,
  work_involves_inu: false,
  employment_history: "",
  // Previous Certifications
  has_recent_oeuk_exam: "",
  recent_oeuk_exam_date: "",
  recent_oeuk_exam_provider: "",
  has_recent_training: "",
  recent_training_date: "",
  recent_training_provider: "",
  has_next_foet: "",
  next_foet_bosiet_date: "",
  // Health Habits
  smoking_status: "",
  smoking_quantity_day: "",
  smoking_time_years: "",
  alcohol_consumption: "",
  physical_activity: "",
  physical_activity_frequency: "",
  physical_activity_duration: "",
  // Occupational Medical History
  occupational_diseases: "",
  workplace_accidents: "",
  medical_evacuations: "",
  missed_trips: "",
  previous_oeuk_deferred: false,
  previous_oeuk_restricted: false,
  // Current Medical History
  current_diagnoses: "",
  undiagnosed_symptoms: "",
  recurring_appointments: "",
  current_medication: "",
  // Medical History
  hospital_admissions: "",
  surgeries: "",
  chronic_diseases: "",
  high_blood_pressure: "",
  cardiovascular_disease: "",
  neurological_disease: "",
  anxiety_depression: "",
  alcohol_use_disorder: "",
  substance_abuse: "",
  asthma: "",
  copd: "",
  pneumothorax: "",
  diabetes: "",
  thyroid_disorder: "",
  addisons_disease: "",
  peptic_ulcer: "",
  inflammatory_bowel_disease: "",
  pancreatitis: "",
  liver_disease: "",
  limb_amputation: "",
  arthritis: "",
  joint_replacement: "",
  muscle_pain: "",
  back_pain: "",
  dermatitis: "",
  kidney_disease: "",
  blood_disorders: "",
  organ_transplantation: "",
  cancer: "",
  infectious_disease: "",
  hearing_loss: "",
  dizziness_vertigo: "",
  eardrum_perforation: "",
  visual_impairment: "",
  caries_dental: "",
  allergic_disorders: "",
  immunodeficiency: "",
  current_pregnancy: "",
  self_perception_disability: "",
  classified_disabled: "",
};
